### ISSUE TITLE
Run program from the command line

### ISSUE THREAD

**Issue by vladimirkovacevic** [mionarankovic/variant-calling-algorithm#2]
The majority of bioinformatics tools are able to be run from command line. Please make this variant caller as python script that parses cmd line arguments (pileup name and p) and outputs VCF on stdout or in the file if file name with "-o" parameter is given. 
docopt is convenient for this purpose.

**Comment by mionarankovic** [comment]
I uploaded part1_VCF.py script that can be run from the command line. Examples on how to run it are in README.md and at the very beginning of the script.
I found docopt very useful, thank you.
